### ISSUE TITLE
The zero-shot speech synthesis ability is not strong enough!!!

### ISSUE THREAD

**Issue by zazachao** [hcy71o/SC-CNN#8]
Hi author, first of all thank you for the great work of open source. Secondly, I had some minor problems while modifying your model. Specifically, I feed all of the vectors from the reference encoder output into the model, including the text encoder, StochasticDurationPredictor, decoder, generator, and flow, but I don't use KernelPredictor. In addition, bert information is added to the text encoder. Finally, I used about 31 hours of corpus for training a new language, including 66 speakers, but the ability of zero-shot speech synthesis is not strong enough. What is the reason for this? Is it due to the model or the amount of data?

**Comment by hcy71o** [comment]
Thank you for your interest!

I think the current dataset is too small to cover a diverse range of speakers and phonetic contexts.
Additionally, some further suggestions:
Use DDP instead of SDP, 
Feed the speaker vector only into the Flow and Text Encoder.

Lastly, if the training data remains as limited as it is now, I recommend using other systems where the vocoder (decoder) is already pre-trained. In my opinion, F5-TTS is SOTA.
